[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  
[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404
  
[[redirects]]
  from = "/fr/*"
  to = "/fr/404"
  status = 404
  
[[redirects]]
  from = "/es/*"
  to = "/es/404"
  status = 404
